### PR TITLE
Parse mix.lock file

### PR DESCRIPTION
**Pull request by andrew**
Opening this up for @barisbalic to help me finish it off

### CODE REVIEW

**Comment by barisbalic** [comment]
Started small refactor, added lockfile parsing but not encoding as I wanted to tidy that up a bit too.  Added a couple of tests and fixtures, probably need tidying but is a start.

@andrew from the lockfile, is it useful to know the source? github, hex, etc?  I shall add more inclusive fixtures tomorrow or day after.

**Comment by andrew** [comment]
:ok_hand:

**Comment by andrew** [comment]
The source is useful btw

**Comment by andrew** [comment]
@barisbalic I've deployed this and getting 422 errors from both the new `/lock` end point and the old one at `/`

**Pull request merged**
